# You can name this whatever you like, but it should match your actual project
sonar.projectKey=faculty-leave-system
sonar.host.url=http://localhost:9000
sonar.login=sqa_d1aa704ff167263113413b1eace98f3b9ca9ded1

# 1. Point to your source code (exclude tests, coverage, and node_modules)
sonar.sources=backend
sonar.exclusions=__tests__/**, coverage/**, node_modules/**, views/**, public/**, app.js

# 2. Point to where your tests actually live
sonar.tests=backend/__tests__
sonar.test.inclusions=backend/__tests__/**/*.test.js

# 3. Point to the coverage files inside the backend folder
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.testExecutionReportPaths=backend/coverage/test-reporter.xml
